notifications:
  email: false

dist: xenial

language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      python:
        - '2.7'
        - '3.4'
        - '3.5'
        - '3.6'
        - '3.7'
        - 'pypy'
        - 'pypy3.5'
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
        PRE_CMD=linux32
      python:
        - '2.7'
        - '3.4'
        - '3.5'
        - '3.6'
        - '3.7'
        - 'pypy'
        - 'pypy3.5'

install:
  - docker pull $DOCKER_IMAGE
  - pip install codecov
  - pip install -r requirements.txt

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.travis/build-wheels.sh
  - mkdir dist -p
  - cp wheelhouse/* dist
  - ls dist/
  - python setup.py build_ext --inplace
  - coverage run -m test

after_success:
  - codecov