notifications:
  email: false

dist: xenial

language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      python:
        - '2.7'
        - '3.4'
        - '3.5'
        - '3.6'
        - '3.7'
        - 'pypy'
        - 'pypy3.5'
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
        PRE_CMD=linux32
      python:
        - '2.7'
        - '3.4'
        - '3.5'
        - '3.6'
        - '3.7'
        - 'pypy'
        - 'pypy3.5'

install:
  - docker pull $DOCKER_IMAGE
  - pip install codecov
  - pip install -r requirements.txt

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/.travis/build-wheels.sh
  - mkdir dist -p
  - cp wheelhouse/* dist
  - ls dist/
  - python setup.py build_ext --inplace
  - coverage run -m test

after_success:
  - codecov

deploy:
  provider: pypi
  user: 'isac322'
  password:
    secure: "gHcuYe+JU7nDZTPJKiDoT9SSuhk/Qqz3GaPVC/oxUGC7GL15ycFZSnRaLhRW9Mm9a6IsUdZK/A5EgS+24QCHCkaHwenS0dPV+ujcM5t9H5AjZVlSjd6SKiYUVSZwq3QEo7zOyJYM0qailU9P5uShY3eiEXUxwB0hqrmbS5xAN70iVkbA5OSKHhKEnpvNTZanfB5LQmCNfCDlVprTkot1Wcs8m+sQsvdOWMJNQYeWSEBsD5FLHWzb2W1TcuOSdqLDr6Awy6O2FdWSMldpvgTCUXaTaNT31GXOvs0zFVtHxl5xef3zMRgV585HE4E2+oNdKNqlUswEbZCm/yHrXHlXYSQGibL32V10y7Sga71ug37WvdiOMtQzj8ROMwzlvIt3yfS6U2/hDNbB1jaqGhDkHS4Qz7ljcqYSXVDj1J97AxeMw5KqFOpOCFlzIrIGHZCcXIeykLeLJCDSI8yOzQZYgAJCY9aSFGJzRs5sHgYmIBGJ2Ii2BNcZuCZ2fc6M3RZhedJr3NhKQRMFN+HaMpyQpY+IBcPVpjP5EMAM6NUjpviFZ1lmoOEq/4zl9u9v/FJpDp8qdDPm9QPHrAlbGNrLtpnaOzOAN5Hw3HF8ap3ZqxaYxE38ktpd2HMitVp8dUItwPTHJo6X5EMgxGSqWbLxnVhfcRyKSOMq/gdHJtBdQ0M="
  on:
    all_branches: true
  distributions: 'sdist'
  skip_cleanup: true
  skip_existing: true